matrix:
  docker_prefix:
  - ""
  - arm64v8/
  - arm32v7/
  tag:
  - amd64
  - arm64
  - arm

  include:
  - tag: amd64
    docker_prefix: ""

pipeline:
  glibc:
    when:
      event:
        - tag
    secrets:
    - SCW_ACCESS_KEY
    - SCW_SECRET_KEY
    - SCW_DEFAULT_ORGANIZATION_ID
    image: ${docker_prefix}elixir:1.13
    environment:
      MIX_ENV: prod
    commands:
      - apt-get update && apt-get install -y cmake libmagic-dev rclone zip
      - wget https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_linux_amd64
      - mv scaleway-cli_2.5.1_linux_amd64 scaleway-cli
      - chmod +x scaleway-cli
      - ./scaleway-cli object config install type=rclone
      - echo "import Mix.Config" > config/prod.secret.exs
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.clean --all
      - mix deps.get --only prod
      - mkdir release
      - export PLEROMA_BUILD_BRANCH=develop
      - mix release --path release
      - zip akkoma-${tag}.zip -r release
      - rclone copyto akkoma-${tag}.zip scaleway:akkoma-updates/develop/akkoma-${tag}.zip

  musl:
    when:
      event:
        - tag
    secrets:
    - SCW_ACCESS_KEY
    - SCW_SECRET_KEY
    - SCW_DEFAULT_ORGANIZATION_ID
    group: release
    image: ${docker_prefix}elixir:1.13-alpine
    environment:
      MIX_ENV: prod
    commands:
      - apk add git gcc g++ musl-dev make cmake file-dev rclone wget zip
      - rm -rf release || true
      - rm -rf _build || true
      - rm -rf /root/.mix
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.clean --all 
      - mix deps.get --only prod
      - mix release --path release
      - export PLEROMA_BUILD_BRANCH=develop
      - zip akkoma-${tag}.zip -r release
      - rclone copyto akkoma-${tag}.zip scaleway:akkoma-updates/develop/akkoma-${tag}-musl.zip
