when:
  - event: pull_request

matrix:
  # test the lowest and highest versions
  include:
    - ELIXIR_VERSION: 1.15
      OTP_VERSION: 25
      LINT: NO
      PLATFORM: linux/amd64
    - ELIXIR_VERSION: 1.19
      OTP_VERSION: 28
      LINT: YES
      PLATFORM: linux/arm64

labels:
  platform: ${PLATFORM}

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pleroma_test_${ELIXIR_VERSION}_${OTP_VERSION}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

steps:
  test:
    image: akkoma/ci-base:${ELIXIR_VERSION}-otp${OTP_VERSION}
    environment:
      MIX_ENV: test
      POSTGRES_DB: pleroma_test_${ELIXIR_VERSION}_${OTP_VERSION}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: postgres
      LINT: ${LINT}
    commands:
      - sh -c 'uname -a && cat /etc/os-release || :'
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix compile
      - test "${LINT}" = "NO" || mix format --check-formatted
      - mix ecto.drop -f -q
      - mix ecto.create
      - mix ecto.migrate
      - mkdir -p test/tmp
      - mix test --preload-modules --exclude erratic --exclude federated --exclude mocked || mix test --failed
      - mix test --preload-modules --only mocked || mix test --failed
